"""
工具数据定义
"""

# 工具数据
tools_data = [
  {
    'id': 'cursor',
    'name': 'Cursor',
    'description': '基于 VS Code 构建的 AI 优先代码编辑器，提供先进的 AI 功能以提高编码效率。',
    'longDescription': 'Cursor 是一款将先进的 AI 功能直接集成到编码环境中的 AI 优先代码编辑器。基于 Visual Studio Code 构建，Cursor 提供智能代码补全、代码生成和上下文感知辅助等功能，旨在简化开发流程并提高生产力。',
    'features': [
      '智能代码补全',
      '代码生成',
      '上下文感知辅助',
      '与 VS Code 扩展集成',
      'AI 辅助编码的作曲家和代理模式',
    ],
    'pricing': '免费版本，可选付费高级功能',
    'website': 'https://www.cursor.com/',
    'icon': 'https://www.cursor.com/favicon.ico',
  },
  {
    'id': 'trae',
    'name': 'Trae',
    'description': '字节跳动开发的 AI 驱动的 IDE，提供自适应 AI 编码辅助功能。',
    'longDescription': 'Trae 是由字节跳动开发的 AI 驱动的集成开发环境（IDE），集成了自适应 AI 功能来辅助开发者进行编码任务。基于 Visual Studio Code 构建，Trae 提供代码补全、基于注释的代码生成和上下文感知建议等功能，旨在提高编码效率和生产力。',
    'features': [
      '自适应 AI 代码补全',
      '基于注释的代码生成',
      '上下文感知建议',
      '与 VS Code 扩展集成',
      '用户友好界面',
    ],
    'pricing': '目前免费',
    'website': 'https://www.trae.ai/',
    'icon': 'https://lf-cdn.trae.com.cn/obj/trae-com-cn/trae_website_prod_cn/static/image/favicon.ico',
  },
  {
    'id': 'zed',
    'name': 'Zed',
    'description': '专注于速度和效率的 AI 增强代码编辑器，具有 AI 辅助编码功能。',
    'longDescription': 'Zed 是一款强调速度和效率的 AI 增强代码编辑器。它集成了旨在提高开发者生产力的 AI 辅助编码功能，提供轻量级和响应迅速的编码环境。',
    'features': [
      'AI 辅助代码补全',
      '轻量级和快速性能',
      '用户友好界面',
      '与版本控制系统集成',
      '可自定义设置',
    ],
    'pricing': '免费版本，可选付费高级功能',
    'website': 'https://www.zed.dev/',
    'icon': 'https://zed.dev/favicon_black_16.png',
  },
  {
    'id': 'bolt-new',
    'name': 'Bolt.new',
    'description': '浏览器版 VS Code 环境，支持一键部署到 Netlify，集成 AI 代码生成。',
    'longDescription': 'Bolt.new 由 StackBlitz 开发，将完整的 VS Code 体验带入浏览器，并提供一键部署到 Netlify 的功能。这个强大的平台将 AI 驱动的代码生成与完整的开发环境相结合，让您可以在浏览器中创建、编辑和部署全栈应用。通过原生 Node.js 执行和实时协作功能，Bolt.new 无需本地环境设置即可提供专业级的开发体验。',
    'features': [
      '浏览器中的完整 VS Code 体验',
      '一键部署到 Netlify',
      'AI 驱动的代码生成',
      '原生 Node.js 执行',
      '实时协作功能',
    ],
    'pricing': '免费版本，可选付费高级功能',
    'website': 'https://bolt.new/',
    'icon': 'https://bolt.new/static/favicon.svg',
  },
  {
    'id': 'lovable-dev',
    'name': 'Lovable.dev',
    'description': '支持即时分享的 AI 代码生成器，具备协作和代码审查功能。',
    'longDescription': 'Lovable.dev 是一个创新的 AI 驱动代码生成器，特别强调协作和分享功能。其独特之处在于开发者可以通过链接即时分享生成的代码和开发工作流程，非常适合代码审查和结对编程。该平台擅长处理复杂的业务逻辑，同时保持清晰的代码架构，其可分享的工作空间链接使团队协作变得轻而易举。',
    'features': [
      '通过链接即时分享代码',
      'AI 驱动的代码生成',
      '协作代码审查',
      '复杂业务逻辑处理',
      '清晰代码架构维护',
    ],
    'pricing': '免费版本，可选付费高级功能',
    'website': 'https://lovable.dev/',
    'icon': 'https://lovable.dev/favicon.ico',
  },
  {
    'id': 'vscode-copilot',
    'name': 'VScode + GitHub Copilot',
    'description': '集成到 Visual Studio Code 中的 AI 驱动代码补全和结对编程助手。',
    'longDescription': 'GitHub Copilot 是集成到 Visual Studio Code 中的 AI 结对编程工具，基于代码上下文提供实时代码建议和自动补全。它帮助开发者更快地编写代码并减少错误，支持多种编程语言和框架。',
    'features': [
      '实时代码建议',
      '上下文感知自动补全',
      '支持多种编程语言',
      '内联代码解释聊天',
      '与 Visual Studio Code 集成',
    ],
    'pricing': '免费计划提供每月 2,000 次代码补全和 50 次聊天请求；Pro 计划提供无限访问',
    'website': 'https://code.visualstudio.com/docs/copilot/overview',
    'icon': 'https://code.visualstudio.com/favicon.ico',
  },
  {
    'id': 'windsurf',
    'name': 'Windsurf',
    'description': '设计用于通过即时 AI 辅助保持开发者心流状态的 AI 辅助代码编辑器。',
    'longDescription': 'Windsurf 是由 Codeium 开发的 AI 辅助代码编辑器，集成了 AI 功能以提高编码效率。它提供代码生成、上下文感知辅助和用户友好界面等功能，旨在保持开发者的心流状态。',
    'features': [
      'AI 驱动的代码生成',
      '上下文感知辅助',
      '用户友好界面',
      '与现有工作流程集成',
      '免费访问专业级功能',
    ],
    'pricing': '免费',
    'website': 'https://codeium.com/windsurf',
    'icon': 'https://codeium.com/favicon.ico',
  },
  {
    'id': 'project-idx',
    'name': 'Project IDX',
    'description': 'Google 开发的浏览器版 VS Code 环境，支持全栈开发。',
    'longDescription': 'Project IDX 是 Google 推出的浏览器版完整 VS Code 环境，提供强大的云端开发体验。内置支持 Flutter、Firebase 等 Google 技术，无需本地设置即可提供完整的 IDE 功能。平台包含 AI 编码辅助、实时协作功能，并与 Google Cloud 服务无缝集成，非常适合全栈和跨平台开发。',
    'features': [
      '浏览器中的完整 VS Code 体验',
      '内置 Flutter 和 Firebase 支持',
      'AI 辅助开发',
      '云端工作空间',
      '实时协作功能',
    ],
    'pricing': 'Project IDX 核心功能免费。未来可能会对额外功能收费。',
    'website': 'https://idx.dev/',
    'icon': 'https://idx.dev/apple-touch-icon.png',
  },
  {
    'id': 'replit',
    'name': 'Replit',
    'description': '浏览器版 VS Code 环境，集成部署和实时协作功能。',
    'longDescription': 'Replit 在浏览器中提供完整的 VS Code 开发环境，将强大的编码功能与即时部署能力相结合。其突出特点包括实时协作、集成托管服务和通过 Replit Ghost 提供的 AI 辅助。平台支持超过 50 种编程语言，并通过熟悉的 VS Code 界面提供综合开发环境，包括多人协作编码会话、集成数据库和自动 HTTPS 部署等功能。',
    'features': [
      '浏览器中的完整 VS Code 体验',
      '实时协作编码',
      '集成托管和部署',
      'Replit Ghost AI 辅助',
      '内置数据库支持',
    ],
    'pricing': '提供基本功能的免费计划，个人付费计划起价 $7/月，团队计划 $40/用户/月',
    'website': 'https://replit.com/',
    'icon': 'https://cdn.replit.com/dotcom/favicon-196.png',
  },
]